### ISSUE TITLE
Multiple components as ES6 classes and vulcanize

### ISSUE THREAD

**Issue by davidcv5** [ebidel/polymer-experiments#8]
@ebidel I'm adding this as an issue since I'm not sure what's the best way to ask for your help.

After looking at your awesome talk at **Polymer Dev Summit** I decided to give it a try to **ES6** classes in Polymer. So basically I started from PSK, followed all steps to make it ES6 compatible and added 2 custom elements, which I converted to ES6 classes. So the issue is that before converting them to classes, I ran **gulp** and it was just fine.. but after the conversion, running **gulp** shows the following message:

**Ignoring duplicate element definition: undefined**

I'm not sure if this is an issue with Babeljs or what, I hope you could help me figure it out.. thanks in advance!!!

**Comment by ebidel** [comment]
That looks like an error coming from gulp-vulcanize: https://github.com/Polymer/vulcanize/issues/164

Check that you're setting the `is` property correctly for your element name.

**Comment by davidcv5** [comment]
@ebidel first of all.. thanks for the reply!

The `is` is fine, and actually, each element is vulcanized properly, no error message, when only one of them is included in `elements.html`, but if I add more than one, then the error shows.. once for each additional element that I add to `elements.html`.

Again... thank you!!

**Comment by ebidel** [comment]
Can you post code?

**Comment by davidcv5** [comment]
@ebidel here is the code https://github.com/davidcv5/es2015-vulcanize

Basically, these are the steps I followed:

1 - `$ yo polymer`
2 - Added ES2015 support following the steps described here https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md
3 - Ran `$ gulp` to confirm everything was fine. No error message.
4 - Changed `my-list.html` and `my-greeting.html` to ES2015 classes.
5 - Ran `$ gulp` to build the project and it showed the error message
**Ignoring duplicate element definition: undefined**

**Comment by ebidel** [comment]
I checked out the code. It doesn't seem to be a fatal error, right? Things get compiled and the app works. 

Definitely a problem with PSK's build process.  I'm not too familiar with it but there's something weird about what it's doing.  I think what's happening is that it compiles + vulcanizes the elements, individually, then `gulp` does the same for index.html. That's just a hunch though. Filed: https://github.com/PolymerElements/polymer-starter-kit/issues/420

**Comment by ebidel** [comment]
I'm going to close this in favor of that bug.

**Comment by davidcv5** [comment]
@ebidel Awesome.. thanks Eric! 
Yes, it's not a fatal error, more like some issues with the build process as you mentioned. Thanks for the help and everything!
